"""empty message

Revision ID: 7c024fa5d8ad
Revises: 
Create Date: 2024-01-21 11:24:24.257471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c024fa5d8ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_token_key', type_='unique')
        batch_op.drop_column('token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('users_token_key', ['token'])

    # ### end Alembic commands ###
